version: '3.1'
services:
  belkamen: 
    image: belkamen:latest
    container_name: belkamen-api
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
    depends_on:
      - mysql
    restart: always

  mysql:
    container_name: mysql 
    image: mysql:latest
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
